

CREATE DATABASE CINE;

USE CINE;

CREATE TABLE PELICULAS (
ID_PELICULA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PELICULA VARCHAR(20) NOT NULL UNIQUE,
DURACION INT NOT NULL 
);

ALTER TABLE PELICULAS MODIFY NOMBRE_PELICULA VARCHAR(45);

CREATE TABLE SALAS (
ID INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(20) NOT NULL,
NUMERO_ASIENTOS INT NOT NULL 
);

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) ,
APELLIDO VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE FUNCIONES (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PELICULA INT NOT NULL , 
ID_SALA INT NOT NULL ,
HORA_INICIO DATETIME NOT NULL,
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULAS(ID_PELICULA),
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);

CREATE TABLE ASIENTOS (
ID_ASIENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FILA CHAR(1) NOT NULL ,
NUMERO INT NOT NULL,
ID_SALA INT NOT NULL ,
FOREIGN KEY (ID_SALA) REFERENCES SALAS (ID)
);

CREATE TABLE RESERVACIONES (
ID INT PRIMARY KEY AUTO_INCREMENT ,
ID_FUNCION INT NOT NULL ,
ID_CLIENTE INT NOT NULL ,
FOREIGN KEY (ID_FUNCION) REFERENCES FUNCIONES(ID) ,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

CREATE TABLE ASIENTOS_RESERVADOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
ID_RESERVACIONES INT NOT NULL ,
ID_ASIENTOS INT NOT NULL ,
FOREIGN KEY (ID_RESERVACIONES) REFERENCES RESERVACIONES(ID) ,
FOREIGN KEY (ID_ASIENTOS) REFERENCES ASIENTOS(ID_ASIENTO) 
);

