SELECT * FROM SAKILA.ACTOR; 
SELECT ACTOR_ID, FIRST_NAME, LAST_NAME, LAST_UPDATE FROM SAKILA.ACTOR;

SELECT ACTOR_ID, FIRST_NAME AS NOMBRE, LAST_NAME AS APELLIDO FROM SAKILA.ACTOR; #DE ESTA MANERA MODIFICO LOS CAMPOS PARA PRESENTARLOS DE LA MANERA QUE QUIERA ESTO NO IMPLICA QUE SE MODIFIQUEN POR COMPLETO SINO AL MOMENTO DE PRESENTAR LA TABLA

SELECT * FROM SAKILA.CITY;

SELECT CITY AS CIUDAD, COUNTRY_ID AS NUMERO_PAIS FROM SAKILA.CITY; #SOLO ESTAMOS MODIFICANDO LOS NOMBRES AL MOMENTO DE LA SALIDA (REVISALO) 

SELECT * FROM SAKILA.CUSTOMER;

SELECT DISTINCT (STORE_ID) FROM SAKILA.CUSTOMER; #DE ESTA MANERA CONSULTAMOS LOS VALORES QUE SON DISTINTOS DENTRO DE UNA COLUMNA ESPECIFICA

SELECT * FROM SAKILA.PAYMENT;

SELECT DISTINCT (CUSTOMER_ID) FROM SAKILA.PAYMENT;#ESTAMOS RECUPERANDO VALORES UNICOS.

SELECT * FROM SAKILA.COUNTRY;

SELECT * FROM SAKILA.COUNTRY ORDER BY COUNTRY DESC; # DE ESTA MANERA SE ORDENAN LOS DATOS DE UNA TABLA DE MANERA DESCENDENTE (DE MAYOR A MENOR)
SELECT COUNTRY AS PAISES FROM SAKILA.COUNTRY ORDER BY COUNTRY ASC; #DE ESTA MANERA ESTOY SELECCIONANDO UNA TABLA Y ORDENANDOLA DE MENOR A MAYOR 

SELECT * FROM SAKILA.CUSTOMER;
SELECT FIRST_NAME AS PRIMER_NOMBRE FROM SAKILA.CUSTOMER ORDER BY FIRST_NAME ASC; 

SELECT STORE_ID AS ID_ALMACEN, FIRST_NAME AS PRIMER_NOMBRE, LAST_NAME AS APELLIDOS FROM SAKILA.CUSTOMER; 
SELECT STORE_ID AS TIENDA, FIRST_NAME AS NOMBRE, LAST_NAME AS APELLIDO FROM SAKILA.CUSTOMER; 
SELECT LAST_NAME AS APELLIDO FROM SAKILA.CUSTOMER ORDER BY LAST_NAME DESC; 

SELECT * FROM SAKILA.PAYMENT;
SELECT DISTINCT (AMOUNT) AS MONTO FROM SAKILA.PAYMENT ORDER BY AMOUNT ASC; #AQUI MOSTRAMOS LOS VALORES UNICOS DENTRO DE LA COLUMNA DE MONTO(AMOUNT) Y LOS ORDENAMOS DE MANERA ASCENDENTE






