SELECT * FROM SAKILA.ACTOR WHERE FIRST_NAME = "DAN"; # DE ESTA MANERA CONSULTAMOS TODOS LOS REGISTROS CON EL NOMBRE DAN

SELECT * FROM SAKILA.CITY WHERE COUNTRY_ID = 102; #BUSCANDO LOS REGISTROS DONDE COUNTRY_ID SEA IGUAL A 102;

SELECT * FROM SAKILA.CUSTOMER;

SELECT * FROM SAKILA.CUSTOMER WHERE STORE_ID = 1;# TRAER TODOS LOS CLIENTE QUE SE HAYAN REGISTRADO EN LATIENDA NUMERO 1

SELECT CUSTOMER_ID AS CLIENTE_ID, STORE_ID AS TIENDA_ID, FIRST_NAME AS PRIMER_NOMBRE, LAST_NAME AS APELLIDO, EMAIL AS CORREO FROM SAKILA.CUSTOMER ORDER BY CUSTOMER_ID, STORE_ID, FIRST_NAME ASC; #AQUI CAMBIAMOS LOS NOMBRES DE LOS CAMPOS Y LUEGO ORDENAMOS ALGUNOS DE ELLOS DE MANERA ASCENDENTE PARA POSTERIORMENTE PRESENTAR LA TABLA

SELECT * FROM SAKILA.INVENTORY;

SELECT * FROM SAKILA.INVENTORY WHERE FILM_ID > 50; #AQUI ESTAMOS PRESENTANDO TODOS LOS REGISTROS DONDE FILM_ID ES MAYOR A 50

SELECT * FROM SAKILA.PAYMENT;
SELECT DISTINCT (AMOUNT) FROM SAKILA.PAYMENT WHERE AMOUNT < 3 ORDER BY AMOUNT DESC; 
SELECT DISTINCT (AMOUNT) FROM SAKILA.PAYMENT WHERE AMOUNT < 3 ORDER BY AMOUNT ASC;

SELECT * FROM SAKILA.STAFF;

SELECT * FROM SAKILA.STAFF WHERE STAFF_ID = 1; # BUSCANDO EN LA TABLA PERSONAS DE LA DB SAKILA TODO LO RELACIONADO CON STAFF_ID 

SELECT NAME AS IDIOMA FROM SAKILA.LANGUAGE WHERE NAME <> 'GERMAN' ORDER BY NAME ASC;

SELECT * FROM SAKILA.FILM;

SELECT DESCRIPTION AS DESCRIPCION, RELEASE_YEAR AS AÑO_LANZAMIENTO FROM SAKILA.FILM;

DESCRIBE SAKILA.FILM;

SELECT * FROM SAKILA.FILM WHERE TITLE = 'IMPACT ALADDIN';

SELECT * FROM SAKILA.PAYMENT;

SELECT * FROM SAKILA.PAYMENT WHERE AMOUNT > 0.99 ORDER BY AMOUNT ASC;

