USE BODEGA; #USAMOS LA DB BODEGA

CREATE TABLE PERSONAS (
ID INT AUTO_INCREMENT PRIMARY KEY ,
NOMBRE VARCHAR(20) ,
EDAD INT ,
PAIS VARCHAR(20)
); # CREAMOS UNA NUEVA TABLA CON CUATRO CAMPOS Y A UNO(id) LE ASIGNAMOS UN AUTO INCREMENTO

SELECT * FROM PERSONAS;# MOSTRAMOS EL CONTENIDO DE LA TABLA CREADA

INSERT INTO PERSONAS ( NOMBRE , EDAD , PAIS) #INSERTAMOS NUEVOS NUEVOS VALORES EN LOS CAMPOS ANTERIORES
VALUES ("JOHAN" , 90, "COLOMBIA"); #PASAMOS LOS VALORES


SET SQL_SAFE_UPDATES = 0; #CON ESTO PODEMOS VARIAR EL ATRIBUTO CON EL QUE ESPECIFICAMOS LA FILA QUE SE VA A ELIMINAR

DELETE FROM PERSONAS # AQUI VAMOS A ELIMINAR UNA FILA DE LA TABLA, PARA ELLO UTILIZAMOS DELETE FROM
WHERE NOMBRE = "JOHAN"; #PROPORCIONAMOS UN NOMBRE(ATRIBUTO) PARA IDENTIFICAR LA FILA A ELIMINAR

SELECT * FROM PERSONAS;#VOLVEMOS A MOSTRAR EL CONTENIDO DE PERSONAS PARA VERIFICAR QUE YA SE HAYA ELIMINADO

INSERT INTO PERSONAS (NOMBRE, EDAD, PAIS)#INSERTAMOS VARIAS FILAS A LA VEZ
VALUES ("JUAN", 29, "MEXICO"),
("RICARDO", 29, "COLOMBIA"),
("PEDRO", 38, "PERU");

SELECT * FROM PERSONAS;#VOLVEMOS A MOSTRAR EL CONTENIDO DE LA TABLA PERSONAS

DELETE FROM PERSONAS
WHERE PAIS = "COLOMBIA";
SELECT * FROM PERSONAS;

DELETE FROM PERSONAS;#DE ESTA MANERA ELIMINAMOS TODAS LAS FILAS DE LA TABLA

SELECT * FROM PERSONAS;

DESCRIBE PERSONAS;




