USE SAKILA;

SELECT * FROM ACTOR;

DESCRIBE ACTOR;

INSERT INTO SAKILA.ACTOR ( FIRST_NAME, LAST_NAME)
VALUES ("JHON" , "CENA"),
("FIORELA", "GUELINI"),
("RICARDO", "MORALES"),
("PETER", "PARKER");

SELECT * FROM SAKILA.ACTOR;


