USE BODEGA; #USAMOS LA DB BODEGA

CREATE TABLE EMPLEADOS (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
APELLIDO VARCHAR(20),
NOMBRE VARCHAR(20) ,
EDAD INT NOT NULL ,
LOCAL_NOMBRE VARCHAR(20) DEFAULT "SIN NOMBRE" ,# SI NO SE PROPORCIONA NINGUN NOMBRE, ENTONCES POR DEFAULT SE COLOCA SIN NOMBRE(ASI LO ESTABLECIMOS EN ESTA LINEA)
CONSTRAINT CK_EDAD CHECK (EDAD >= 18) #AQUI SE AÑADE UNA RESTRICCIÓN PARA VERIFICAR QUE LA EDAD PROPORCIONADA SEA MAYOR O IGUAL A 18 AÑOS
);#CREAMOS UNA NUEVA TABLA

DESCRIBE EMPLEADOS; # MOSTRAMOS LA ESTRUCTURA Y TIPOS DE DATOS DE LA TABLA , INCLUYENDO PK, CONSTRAINT Y DEMAS COSAS 
 
SELECT * FROM EMPLEADOS;#AQUI MOSTRAMOS EL CONTENIDO DE LA TABLA
 
INSERT INTO EMPLEADOS (APELLIDO, NOMBRE, EDAD)
VALUES("MENDES", "CAMILA", 21);#AQUI INSERTAMOS UN PRIMER REGISTRO
 
SELECT * FROM EMPLEADOS; #VOLVEMOS A MOSTRAR EL CONTENIDO DE LA TABLA
 
INSERT INTO EMPLEADOS (APELLIDO, NOMBRE, EDAD ) 
VALUES ("VITOLA","MAYRA", 15); #AQUI PROBAMOS UNA RESTRICCION (CHECK) PARA VER COMO RESPONDE ANTE UN VALOR QUE NO PERMITE
 
ALTER TABLE EMPLEADOS
ALTER EDAD SET DEFAULT 19;#AQUI AÑADIMOS UN DEFAULT POR SI EL USUARIO NO PROPORCIONA SU EDAD. LA EDAD POR DEFAULT SERÁ 19
 
INSERT INTO EMPLEADOS ( APELLIDO, NOMBRE)
VALUES ("MORALES", "RICARDO");#VOLVEMOS A INSERTAR UN REGISTRO PARA ANALIZAR EL FUNCIONAMIENTO DEL NUEVO DEFAULT ESTABLECIDO
 
SELECT * FROM EMPLEADOS;#MOSTRAMOS EL NUEVO CONTENIDO DE LA TABLA

 