#CREATE DATABASE EJERCICIOS;

USE EJERCICIOS;


#CREATE TABLE MASCOTAS (
#ID INT NOT NULL ,
#NOMBRE VARCHAR(20) ,
#ID_DUEÑO INT NOT NULL , 
#SERVICIO VARCHAR (20) ,
#PRIMARY KEY (ID)
#);

#CREATE TABLE PERSONAS (
#ID INT NOT NULL ,
#APELLIDO VARCHAR(20),
#COD_ZIP INT NOT NULL ,
#TLF CHAR(12) ,
#PRIMARY KEY (ID)
#);

#CREATE TABLE DIRECCIONES (
#ZIP INT NOT NULL ,
#NOMBRE_ZONA VARCHAR(20),
#RUTA VARCHAR(20)
#);

#ALTER TABLE MASCOTAS 
#ADD CONSTRAINT FK_DUEÑOS_ID
#FOREIGN KEY (ID_DUEÑO) REFERENCES MASCOTAS(ID);
#DESCRIBE MASCOTAS;

ALTER TABLE EJERCICIOS.PERSONAS
ADD CONSTRAINT FK_DIRECCIONES_ZIP #SE AÑADE UN NOMBRE QUE IDENTIFICA A LA RESTRICCION
FOREIGN KEY (COD_ZIP) REFERENCES EJERCICIOS.DIRECCIONES(ZIP);

#ALTER TABLE PERSONAS 
#ADD COLUMN EMAIL VARCHAR(20);
#DESCRIBE PERSONAS;

#ALTER TABLE PERSONAS
#ADD CONSTRAINT U_EMAIL UNIQUE(EMAIL);
#DESCRIBE PERSONAS;

#ALTER TABLE MASCOTAS CHANGE NOMBRE PRIMER_NOMBRE VARCHAR(20);
#ALTER TABLE MASCOTAS REMANE NOMBRE TO PRIMER_NOMBRE; #Otra manera de cambiar el nombre(atributo) de una columna 
#DESCRIBE MASCOTAS;

#ALTER TABLE DIRECCIONES MODIFY RUTA CHAR(12);
#DESCRIBE DIRECCIONES;